// Generates tailwind/theme.css from tailwind/tokens.ts semantic colors.
// Source of truth is tokens.ts (hex) — never hand-edit theme.css, run `pnpm gen:theme` instead.

import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { tokens } from "../tailwind/tokens";

function hexToHslTriplet(hex: string): string {
  const clean = hex.replace("#", "");
  const r = parseInt(clean.slice(0, 2), 16) / 255;
  const g = parseInt(clean.slice(2, 4), 16) / 255;
  const b = parseInt(clean.slice(4, 6), 16) / 255;

  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const l = (max + min) / 2;

  let h = 0;
  let s = 0;

  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r:
        h = (g - b) / d + (g < b ? 6 : 0);
        break;
      case g:
        h = (b - r) / d + 2;
        break;
      case b:
        h = (r - g) / d + 4;
        break;
    }
    h /= 6;
  }

  return `${Math.round(h * 360)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`;
}

function toKebabCase(value: string): string {
  return value.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
}

function flattenToCssVars(group: Record<string, unknown>): string[] {
  const lines: string[] = [];
  for (const [category, values] of Object.entries(group)) {
    for (const [key, hex] of Object.entries(values as Record<string, string>)) {
      const varName = key === "DEFAULT" ? `--${category}` : `--${category}-${toKebabCase(key)}`;
      lines.push(`  ${varName}: ${hexToHslTriplet(hex)};`);
    }
  }
  return lines;
}

const lightLines = flattenToCssVars(tokens.semantic.light);
const darkLines = flattenToCssVars(tokens.semantic.dark);

const css = `/* AUTO-GENERATED by scripts/generate-theme.ts — do not edit by hand. */
/* Edit tokens/*.json and run \`pnpm gen:theme\` to regenerate. */

:root {
${lightLines.join("\n")}
}

.dark {
${darkLines.join("\n")}
}
`;

writeFileSync(join(__dirname, "../tailwind/theme.css"), css);
console.log("theme.css generated from tokens.ts");
