// Generates tailwind/theme.css from the resolved semantic colors in tailwind/tokens.ts.
// Source of truth is tokens/*.json (hex) — never hand-edit theme.css, run `pnpm gen:theme` instead.

import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { tokens } from "../tailwind/tokens";

function toKebabCase(value: string): string {
  return value.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
}

function flattenToCssVars(group: Record<string, unknown>): string[] {
  const lines: string[] = [];
  for (const [category, values] of Object.entries(group)) {
    for (const [key, hex] of Object.entries(values as Record<string, string>)) {
      const varName = key === "DEFAULT" ? `--${category}` : `--${category}-${toKebabCase(key)}`;
      lines.push(`  ${varName}: ${hex};`);
    }
  }
  return lines;
}

const lightLines = flattenToCssVars(tokens.semantic.light);
const darkLines = flattenToCssVars(tokens.semantic.dark);

const css = `/* AUTO-GENERATED by scripts/generate-theme.ts — do not edit by hand. */
/* Edit tokens/*.json and run \`pnpm gen:theme\` to regenerate. */

:root {
${lightLines.join("\n")}
}

.dark {
${darkLines.join("\n")}
}
`;

writeFileSync(join(__dirname, "../tailwind/theme.css"), css);
console.log("theme.css generated from tokens.ts");
